jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change Directory (Check if Exists)
        run: |
          ls -R  # Debug: Show all files in the runner
          cd LAB7/LAB7 || exit 1  # Exit if directory does not exist
          
      - name: Build Docker Image
        run: docker build -t my-html-app .
