name: Docker Build & Deploy

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-html-app .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 my-html-app

      - name: Verify Container
        run: curl -I http://localhost:8080
