name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to the correct directory
        run: cd LAB7/LAB7  # Adjust this if your Dockerfile is in a different path

      - name: List files (for debugging)
        run: ls -R

      - name: Build Docker Image
        run: docker build -t my-html-app .
